# Compose the website from the front and back ends, plus an npx static file server
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://backend:5174 
      - DATABASE_FILE=/app/test.db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5174:5174"

  static-server:
    image: node:20
    hostname: "content"
    ports:
      - "8080:8080"
    # serve the game_thumbnails directory 
    command: npx serve -l 8080 -s game_thumbnails