name: Build & Deploy Zola Static Site

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    name: Publish site 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.22.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
